# Rime default settings
# encoding: utf-8

# Fork From: https://github.com/rime/librime/blob/3bc65c990546aa2062ecd1eb593d54d2949644cd/data/minimal/default.yaml
config_version: "2025.05"

# 以下内容, 实际会由 default.custom.yaml 和输入法 schema 配置所覆写
schema_list:
  - schema: rome

switcher:
  # 切换方案时显示的标题
  caption: 〔方案切换〕
  # 切换方案的快捷键
  hotkeys:
    - Control+Shift+grave
    # F4 和 JetBrains 的快捷键冲突
    # - F4
  # 在切换方案时保留的选项
  save_options:
    - full_shape # 保留全角模式
    - ascii_punct # 保留西文模式
    - transcription # 保留汉字简繁体选项
    - emoji_suggestion # Emoji
  # 折叠选项以节省空间，多方案时建议折叠 true ，一个方案建议展开 false
  fold_options: true
  # 对选项进行缩写
  abbreviate_options: true
  # 选项之间的分隔符
  option_list_separator: "／"

menu:
  # 候选词个数
  page_size: 6

translator:
  # 启用自动造词
  enable_encoder: true
  # 启用自动句子输入
  enable_sentence: true
  # 启用用户词典
  enable_user_dict: true
  # 对已上屏的词语进行自动编码以提高下次输入的命中率
  encode_commit_history: true

punctuator:
  full_shape:
    " ": { commit: "　" }
    ",": { commit: ， }
    ".": { commit: 。 }
    "<": [《, 〈, «, ‹]
    ">": [》, 〉, », ›]
    "/": [／, ÷]
    "?": { commit: ？ }
    ";": { commit: ； }
    ":": { commit: ： }
    "'": { pair: ["‘", "’"] }
    '"': { pair: ["“", "”"] }
    '\': [、, ＼]
    "|": [・, ｜, "§", "¦"]
    "`": ｀
    "~": [〜, ～, 〰]
    "!": { commit: ！ }
    "@": [＠, ☯]
    "#": [＃, ⌘]
    "%": [％, "°", "℃"]
    "$": [￥, "$", "€", "£", "¥", "¢", "¤"]
    "^": { commit: …… }
    "&": ＆
    "*": [＊, ・, ·, ×, ※, ❂]
    "(": （
    ")": ）
    "-": －
    "_": ——
    "+": ＋
    "=": ＝
    "[": [「, 【, 〔, ［]
    "]": [」, 】, 〕, ］]
    "{": [『, 〖, ｛]
    "}": [』, 〗, ｝]
  half_shape:
    ",": { commit: ， }
    ".": { commit: 。 }
    "<": [《, 〈, «, ‹]
    ">": [》, 〉, », ›]
    "/": [、, "/", ／, ÷]
    "?": { commit: ？ }
    ";": { commit: ； }
    ":": { commit: ： }
    "'": { pair: ["‘", "’"] }
    '"': { pair: ["“", "”"] }
    '\': [、, '\', ＼]
    "|": [・, "|", ｜, "§", "¦"]
    "`": "`"
    "~": ["~", 〜, ～, 〰]
    "!": { commit: ！ }
    "@": "@"
    "#": "#"
    "%": ["%", ％, "°", "℃"]
    "$": [￥, "$", "€", "£", "¥", "¢", "¤"]
    "^": { commit: …… }
    "&": "&"
    "*": ["*", ＊, ・, ·, ×, ※, ❂]
    "(": （
    ")": ）
    "-": "-"
    "_": ——
    "+": "+"
    "=": "="
    "[": [「, 【, 〔, ［]
    "]": [」, 】, 〕, ］]
    "{": [『, 〖, ｛]
    "}": [』, 〗, ｝]

key_binder:
  # import_preset: default
  bindings:
    # has_menu: 有候选字即可
    # paging: 已经至少翻过一页时
    # composing: 打字输入时
    - { when: always, accept: "Control+Shift+E", toggle: emoji } # toggle 值要和前文 switches 中配置的一致
    - { when: always, accept: Control+Shift+1, select: .next } # 选择输入法列表中的下一项
    - { when: always, accept: Control+Shift+2, toggle: ascii_mode } # 切换中英文输入
    - { when: always, accept: Control+Shift+3, toggle: full_shape } # 全半角
    - { when: always, accept: Shift+space, toggle: full_shape }
    - { when: always, accept: Control+Shift+4, toggle: tranditionals } # 简繁体
    - { when: always, accept: Control+Shift+5, toggle: extended_charset } # 扩展词表
    - { when: always, accept: Control+period, toggle: ascii_punct }
    - { when: has_menu, accept: "Control+Shift+T", toggle: tranditionals }
    - { when: paging, accept: minus, send: Page_Up } # - 用于向前翻页
    - { when: paging, accept: comma, send: Page_Up } # , 用于向前翻页
    - { when: has_menu, accept: equal, send: Page_Down } # = 用于向后翻页
    - { when: has_menu, accept: period, send: Page_Down } # . 用于向后翻页
    - { when: predicting, accept: comma, send: comma }
    - { when: predicting, accept: period, send: period }

recognizer:
  # 定义识别码的正则表达式规则
  patterns:
    email: "^[a-z][-_.0-9a-z]*@.*$" # 匹配电子邮件地址
    uppercase: "[A-Z][-_+.'0-9A-Za-z]*$" # 匹配大写字母开头的字符串
    url: "^(www[.]|https?:|ftp:|mailto:).*$|^[a-z]+[.].+$" # 匹配 URL 或域名

ascii_composer:
  # 定义切换到西文模式的快捷键
  switch_key:
    Caps_Lock: commit_code # 按下 Caps Lock 会直接上屏
    Control_L: noop # 按下左 Control 键不做任何操作
    Control_R: noop # 按下右 Control 键不做任何操作
    Shift_L: commit_code # 按下左 Shift 键会直接上屏
    Shift_R: inline_ascii # 按下右 Shift 键会临时切换到西文模式
  good_old_caps_lock: true # 启用经典的 Caps Lock 开启西文模式的方式
